branch-defaults:
  master:
    environment: bet-receiver-env
global:
  application_name: bet-receiver
  default_ec2_keyname: null
  default_platform: 64bit Amazon Linux 2014.09 v1.2.0 running Node.js
  default_region: ap-southeast-2
  profile: eb-cli
  sc: git

packages:
  yum:
    git: []
    gcc: []
    make: []
    openssl-devel: []
    libxml2: []
    libxml2-devel: []
